language: node_js
sudo: false

# libxmljs work-arounds
env:
  - CXX=g++-4.8

addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-4.8

before_install:
    - $CXX --version
    - case ${TRAVIS_NODE_VERSION} in 0.8*|0.10*) npm install -g npm@2 ;; esac
# End libxmljs work-arounds

node_js:
    - "0.10"
    - "iojs-2.5"
    - "4"
    - "5"

